# Prometheus configuration file for scraping SSD metrics

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ssd_metrics'
    static_configs:
      - targets: ['localhost:8000']  # Target where Prometheus metrics are exposed

